# Basic Numpy

Numpy는 선형대수나 수치해석, 푸리에 변환과 같은 고급 연산을 지원하는 패키지입니다.

Numpy의 설치는 readme를 참고해 주세요.

Python에서는 다음 명령어를 통해 Numpy를 import할 수 있습니다.  


In [41]:
import numpy as np


의례적으로 numpy는 np라고 줄여 씁니다.


## Array Initialization

먼저 Numpy Array는 다음과 같은 방법들을 통해 만들 수 있습니다.


In [42]:
# 리스트를 넣어 만들 수 있습니다.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [43]:
# 튜플을 넣어 만들 수도 있습니다.
a = np.array((1, 2, 3))
print(a)


[1 2 3]


In [44]:
# 리스트의 리스트를 통해 만들 수도 있습니다.
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [45]:
# 튜플의 리스트를 넣어 만들 수도 있습니다.
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)


[[1 2 3]
 [4 5 6]]


In [46]:
# Array의 데이터 타입을 강제하기 위해서는 다음과 같이 사용합니다.
a = np.array([1, 2, 3], dtype=np.float64)
print(a)
print(a.dtype)


[1. 2. 3.]
float64


큰 행렬(eg. 256*256)을 만들기 위해서는 다른 방법들을 사용합니다.

In [47]:
# np.zeros는 집어넣은 숫자만큼의 원소를 가지는 array를 생성하고, 이를 0으로 초기화합니다.
a = np.zeros(10)
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [48]:
# 튜플을 넣으면 M*N 영행렬을 생성합니다.
a = np.zeros((256, 256))
print(a)
print(a.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(256, 256)


In [49]:
# np.ones는 집어넣은 숫자만큼의 원소를 가지는 array를 생성하고, 이를 1으로 초기화합니다.
a = np.ones(10)
print(a)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [50]:
# np.ones도 튜플을 넣으면 M*N 행렬을 생성합니다.
a = np.ones((256, 256))
print(a)
print(a.shape)


[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
(256, 256)


In [51]:
# np.full은 크기와 채울 값을 넣으면 원하는 크기의 array를 생성합니다.
a = np.full((256, 256), 0.5)
print(a)
print(a.shape)


[[0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 ...
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]]
(256, 256)


In [52]:
# np.eye는 N*N의 단위행렬을 생성합니다.
a = np.eye(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


다음은 ```for```문에서 주로 사용하는 일정한 interval을 가지는 array를 생성하는 방법을 다룹니다. 

In [53]:
# np.arange는 지정된 범위에서 숫자를 생성합니다.
a = np.arange(10)
print(a)

# np.arange에서 interval을 설정해 줄 수 있습니다.
a = np.arange(10, 20, 2)
print(a)


[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]


In [54]:
# np.linspace는 시작값과 끝값을 넣으면 시작값과 끝값 사이를 등간격으로 N개로 나눈 array를 생성합니다.
a = np.linspace(0, 10, 5)
print(a)


[ 0.   2.5  5.   7.5 10. ]


## Array Operations

이제 Numpy Array들의 연산에 대해 알아봅니다.

### Basic Array Operation

다음과 같은 Numpy Array를 가정합시다.

In [55]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)


[[1 2 3]
 [4 5 6]]


먼저, ```print```를 통해 행렬을 출력할 수 있습니다.


In [56]:
# 행렬 전체를 출력합니다.
print(a)

# 특정 원소만 출력할 수도 있습니다.
print(a[0, 0])


[[1 2 3]
 [4 5 6]]
1


행렬의 차원이나 크기를 찾기 위해서는 다음과 같은 함수를 사용할 수 있습니다.


In [57]:
# 행렬의 차원을 출력합니다.
print(np.ndim(a))
print(a.ndim)

# 행렬의 크기를 튜플로 출력합니다.
print(np.shape(a))

# 행렬의 크기를 변환합니다.
a = a.reshape(2, 2)
print(a)

# 행렬의 원소의 개수를 출력합니다.
print(a.size)


2
2
(2, 3)


ValueError: cannot reshape array of size 6 into shape (2,2)

원소의 데이터 타입을 출력하기 위해서는 ```dtype```을 사용합니다.


In [ ]:
print(a.dtype)


int64


### Matrix Operations

다음과 같은 두 행렬을 가정합시다.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[9, 7], [5, 3]])


In [ ]:
# 행렬의 합을 출력합니다.
print(a + b)

# 행렬의 차를 출력합니다.
print(a - b)

# 행렬의 곱을 출력합니다.
print(a * b)

# 행렬곱을 출력합니다.
print(a @ b)

# 해당 행렬의 제곱을 출력합니다.
print(a**2)

# 해당 행렬의 제곱근을 출력합니다.
print(np.sqrt(a))

# 해당 행렬의 각 원소에 대해 참/거짓을 반환합니다.
print(b < 4)

# np.transpose는 행렬의 행과 열을 바꿔줍니다.
print(np.transpose(a))
print(a.T)


[[10  9]
 [ 8  7]]
[[-8 -5]
 [-2  1]]
[[ 9 14]
 [15 12]]
[[19 13]
 [47 33]]
[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[False False]
 [False  True]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


### Array Statistics

다음과 같은 행렬을 가정합니다.

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
# 행렬의 모든 원소의 합을 출력합니다.
print(np.sum(a))

# 행렬의 모든 원소의 평균을 출력합니다.
print(np.mean(a))

# 행렬의 모든 원소의 표준편차를 출력합니다.
print(np.std(a))

# 행렬의 모든 원소의 분산을 출력합니다.
print(np.var(a))

# 행렬의 모든 원소의 최솟값을 출력합니다.
print(np.min(a))

# 행렬의 모든 원소의 최댓값을 출력합니다.
print(np.max(a))

# axis=0은 행렬의 행을 의미합니다.
# axis=1은 행렬의 열을 의미합니다.
# axis=None은 행렬의 원소들을 의미합니다.
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(np.sum(a, axis=None))

# np.argmax는 최댓값의 인덱스를 출력합니다.
print(np.argmax(a))

# np.argmin는 최솟값의 인덱스를 출력합니다.
print(np.argmin(a))

# np.argsort는 원소의 인덱스를 정렬합니다.
print(np.argsort(a))

# np.sort는 원소들을 정렬합니다.
print(np.sort(a))

# np.flipud는 행렬의 열을 역순으로 출력합니다.
print(np.flipud(a))

# np.fliplr는 행렬의 행을 역순으로 출력합니다.
print(np.fliplr(a))


10
2.5
1.118033988749895
1.25
1
4
[4 6]
[3 7]
10
3
0
[[0 1]
 [0 1]]
[[1 2]
 [3 4]]
[[3 4]
 [1 2]]
[[2 1]
 [4 3]]
